// STATE-SPACE PARAMETERS HEADER 
// automatically generated by acqtools repository 
//pid model
float	Apid[2][2]	={
 	{1.000000000000000e+00,0.000000000000000e+00},
 	{0.000000000000000e+00,9.806219845661894e-01}
 	};
float	Bpid[2][1]	={
 	{8.192000000000000e-01},
 	{5.430305908977720e+00}
 	};
float	Cpid[1][2]	={
 	{5.240960153995372e-01,-5.430305908977720e+00}
 	};
float	Dpid[1][1]	={
 	{1.841666741466602e+03}
 	};
float	xpid[2] 	={ 	0.0e+00,0.0e+00	};

//sh1 model
float	Ash1[2][2]	={
 	{6.461955921434069e-01,-9.667574975876422e-02},
 	{9.667574975876427e-02,9.790745734294136e-01}
 	};
float	Bsh1[2][1]	={
 	{-1.071854901755668e+00},
 	{6.655163876595750e-02}
 	};
float	Csh1[1][2]	={
 	{1.071854901755669e+00,6.655163876595704e-02}
 	};
float	Dsh1[1][1]	={
 	{3.165177448509211e+00}
 	};
float	xsh1[2] 	={ 	0.0e+00,0.0e+00	};

//lpf1 model
float	Alpf1[1][1]	={
 	{9.974898801867140e-01}
 	};
float	Blpf1[1][1]	={
 	{5.006964611965307e-02}
 	};
float	Clpf1[1][1]	={
 	{5.006964611965307e-02}
 	};
float	Dlpf1[1][1]	={
 	{1.255059906642907e-03}
 	};
float	xlpf1[1] 	={ 	0.0e+00	};

// https://github.com/HoriFujimotoLab/AcqTools 
// Thomas Beauduin, HFlab (University of Tokyo) 
