// STATE-SPACE PARAMETERS HEADER 
// automatically generated by acqtools repository 
//tlpf model
float	Atlpf[2][2]	={
 	{9.992625752939093e-01,1.772695107194577e-03},
 	{-1.772695107194799e-03,9.957171850795199e-01}
 	};
float	Btlpf[2][1]	={
 	{-2.982443197720114e-02},
 	{-2.971874743395918e-02}
 	};
float	Ctlpf[1][2]	={
 	{-2.982443197720114e-02,2.971874743395920e-02}
 	};
float	Dtlpf[1][1]	={
 	{1.575175369262504e-06}
 	};
float	xtlpf[2] 	={ 	0.0e+00,0.0e+00	};

// https://github.com/HoriFujimotoLab/AcqTools 
// Thomas Beauduin, HFlab (University of Tokyo) 
