// STATE-SPACE PARAMETERS HEADER 
// automatically generated by acqtools repository 
//tlpf model
float	Atlpf[2][2]	={
 	{9.994471753015419e-01,1.330356037749170e-03},
 	{-1.330356037749281e-03,9.967864632262101e-01}
 	};
float	Btlpf[2][1]	={
 	{-2.582538893308901e-02},
 	{-2.575670171213590e-02}
 	};
float	Ctlpf[1][2]	={
 	{-2.582538893308901e-02,2.575670171213590e-02}
 	};
float	Dtlpf[1][1]	={
 	{8.865924212272071e-07}
 	};
float	xtlpf[2] 	={ 	0.0e+00,0.0e+00	};

// https://github.com/HoriFujimotoLab/AcqTools 
// Thomas Beauduin, HFlab (University of Tokyo) 
