// STATE-SPACE PARAMETERS HEADER 
// automatically generated by acqtools repository 
//tlpf model
float	Atlpf[2][2]	={
 	{9.169810829415324e-01,1.402515063508519e-01},
 	{-1.402515063508522e-01,6.364780702398284e-01}
 	};
float	Btlpf[2][1]	={
 	{-3.066202496687273e-01},
 	{-2.230051015954504e-01}
 	};
float	Ctlpf[1][2]	={
 	{-3.066202496687273e-01,2.230051015954505e-01}
 	};
float	Dtlpf[1][1]	={
 	{1.246242049234419e-02}
 	};
float	xtlpf[2] 	={ 	0.0e+00,0.0e+00	};

// https://github.com/HoriFujimotoLab/AcqTools 
// Thomas Beauduin, HFlab (University of Tokyo) 
