// STATE-SPACE PARAMETERS HEADER 
// automatically generated by acqtools repository 
//vpi model
float	Avpi[1][1]	={
 	{1.000000000000000e+00}
 	};
float	Bvpi[1][1]	={
 	{2.500000000000000e-01}
 	};
float	Cvpi[1][1]	={
 	{-2.407271560724613e-01}
 	};
float	Dvpi[1][1]	={
 	{-2.484198250931836e+00}
 	};
float	xvpi[1] 	={ 	0.0e+00	};

//shp model
float	Ashp[2][2]	={
 	{9.604973063316178e-01,-2.342607652511368e-01},
 	{2.342607652511370e-01,9.573932063715052e-01}
 	};
float	Bshp[2][1]	={
 	{8.689754397809768e-02},
 	{-7.312864914987596e-02}
 	};
float	Cshp[1][2]	={
 	{8.689754397809750e-02,7.312864914987619e-02}
 	};
float	Dshp[1][1]	={
 	{9.454079195155637e-01}
 	};
float	xshp[2] 	={ 	0.0e+00,0.0e+00	};

//lpf model
float	Alpf[2][2]	={
 	{6.958226849459790e-01,3.674778151436217e-01},
 	{-3.674778151436211e-01,3.283448698023577e-01}
 	};
float	Blpf[2][1]	={
 	{-5.723678513242871e-01},
 	{-2.665483827777073e-01}
 	};
float	Clpf[1][2]	={
 	{-5.723678513242870e-01,2.665483827777067e-01}
 	};
float	Dlpf[1][1]	={
 	{8.483554969212680e-02}
 	};
float	xlpf[2] 	={ 	0.0e+00,0.0e+00	};

// https://github.com/HoriFujimotoLab/AcqTools 
// Thomas Beauduin, HFlab (University of Tokyo) 
