EXTLIBS	+= c67x_fastmath.lib
EXOBJS	+= 
OBJS	+= ctrl_current.obj ctrl_friction.obj ctrl_motion.obj ctrl_traject.obj hardw_adc.obj hardw_lin.obj hardw_menc.obj hardw_pev.obj hardw_senc.obj main_hil.obj system_fsm.obj system_math.obj
ctrl_current.obj: 
ctrl_friction.obj: 
ctrl_motion.obj: 
ctrl_traject.obj: 
hardw_adc.obj: 
hardw_lin.obj: 
hardw_menc.obj: 
hardw_pev.obj: 
hardw_senc.obj: 
main_hil.obj: 
system_fsm.obj: 
system_math.obj: 
